#Items that cannot be trashed
trash-blacklist:
  - DIAMOND
  - DIAMOND_BLOCK
  - DIAMOND_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - DIAMOND_PICKAXE
  - DIAMOND_HOE
  - DIAMOND_SHOVEL
  - DIAMOND_AXE
  - DIAMOND_SWORD
  - NETHERITE_INGOT
  - ANCIENT_DEBRIS
  - NETHERITE_SCRAP
  - NETHERITE_HELMET
  - NETHERITE_CHESTPLATE
  - NETHERITE_LEGGINGS
  - NETHERITE_BOOTS
  - NETHERITE_PICKAXE
  - NETHERITE_HOE
  - NETHERITE_SHOVEL
  - NETHERITE_AXE
  - NETHERITE_SWORD
  - NETHERITE_BLOCK
  - BEACON
  - NETHER_STAR
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - BLACK_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - PINK_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - LIME_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - RED_SHULKER_BOX
#Sounds for crafting inventories, if you would like no sound, please write "none"
craft-open-sound: BLOCK_BAMBOO_WOOD_BREAK
anvil-open-sound: BLOCK_ANVIL_USE
cartography-open-sound: UI_CARTOGRAPHY_TABLE_TAKE_RESULT
stonecutter-open-sound: UI_STONECUTTER_TAKE_RESULT
smithing-open-sound: BLOCK_SMITHING_TABLE_USE
grindstone-open-sound: BLOCK_GRINDSTONE_USE
loom-open-sound: ENTITY_VILLAGER_WORK_SHEPHERD
enderchest-open-sound: BLOCK_ENDER_CHEST_OPEN
trash-open-sound: BLOCK_BARREL_OPEN
trash-alert: BLOCK_NOTE_BLOCK_PLING

# locale
open-for-other:
  anvil: "<prefix> <gray>Cartography table opened for <target></gray>"
  cartography: "<prefix> <gray>Cartography table opened for <target></gray>"
  crafting-table: "<prefix> <gray>Crafting table opened for <target></gray>"
  enderchest: "<prefix> <gray>Enderchest opened for <target></gray>"
  loom: "<prefix> <gray>Loom opened for <target></gray>"
  smithing-table: "<prefix> <gray>Smithing table opened for <target></gray>"
  stonecutter: "<prefix> <gray>Stonecutter opened for <target></gray>"
  grindstone: "<prefix> <gray>Grindstone opened for <target></gray>"
  trash: "<prefix> <gray>Trash bin opened for <target></gray>"
trash:
  inventory-name: "<red>Trash bin</red>"
  success-feedback: "<prefix> <gray>Your trashed items have been deleted</gray>"
  blacklist-error: "<prefix> <gold>Hey! You had some items in the trash that are not allowed to be trashed, they've been dropped back on the ground</gold>"
plugin-messages:
  prefix: "<white>[<gradient:aqua:dark_aqua>Simple Inventories<reset><white>]<reset>"
  console-name: "<red>[<dark_red>Console</dark_red>]</red> "
  config-reloaded: "<prefix> <gold>Simple Player Utils Config has been reloaded"
errors:
  syntax: "<red>Sorry, that didn't seem to work. Please check that your syntax is correct, and that you have the proper permissions, and try again.</red>"
  too-many-arguments: "<red>Sorry, you provided too many arguments. Please check your syntax and try again</red>"
  must-be-player: "<red>Only a player may execute this command.</red>"
  invalid-player: "<red>No valid player was supplied. <value> is not the name of a valid online player, please check your spelling and try again</red>"
